### ISSUE TITLE
calendar 组件 只使用时间选择功能时报错。

### ISSUE THREAD

**Issue by asher-fire** [IronPans/freeng#13]
1.`<free-calendar [timeOnly]="true"></free-calendar>`
2. 使用时，出现 如下错误:
        Expression has changed after it was checked. Previous value: 'undefined'. Current value: '14'.
3. 问题出现在calendar.component.ts 文件这段代码中
`        <ng-template #times>
          <div class="free-calendar-time">
            <free-calendar-selector [min]="0" [max]="24" [type]="'h'" [value]="currentHour"
                                    (onChange)="onTimeSelectorChange($event)"></free-calendar-selector>
            <free-calendar-selector [min]="0" [max]="59" [type]="'m'" [value]="currentMinute"
                                    (onChange)="onTimeSelectorChange($event)"></free-calendar-selector>
            <free-calendar-selector [min]="0" [max]="59" [type]="'s'" [value]="currentSecond"
                                    (onChange)="onTimeSelectorChange($event)"></free-calendar-selector>
          </div>
        </ng-template>`

**Comment by asher-fire** [comment]
![2018-02-02_143325](https://user-images.githubusercontent.com/16936239/35720012-e9edb280-0826-11e8-8bc4-ac337f30ed39.jpg)
![2018-02-02_143532](https://user-images.githubusercontent.com/16936239/35720022-f08915a8-0826-11e8-969b-454db17c9fa5.jpg)

**Comment by asher-fire** [comment]
修改建议：
![2018-02-02_172642](https://user-images.githubusercontent.com/16936239/35725994-4a179b50-083e-11e8-9d44-4796f68c76e2.jpg)

**Comment by IronPans** [comment]
@zds-jack 这个不是FreeNG的错误，而是Angular本身的机制，你只需开启enableProdMode()，就不会出现这个问题啦
