### ISSUE TITLE
calendar 组件，选择日期时，点击now时，无法向父组件传递当前日期

### ISSUE THREAD

**Issue by asher-fire** [IronPans/freeng#14]
1.calendar 组件，选择日期时，点击now时，无法向父组件传递当前日期。
2. 修改建议：
![2018-02-02_172346](https://user-images.githubusercontent.com/16936239/35725878-e58f99d0-083d-11e8-9a07-96c0ea726b3f.jpg)
在选择日期点击Now时，向外传递数据。

**Comment by IronPans** [comment]
@zds-jack 在v0.5.2中已经修改
