### ISSUE TITLE
freeng

### ISSUE THREAD

**Issue by RonadoLong** [IronPans/freeng#2]
您好 为什么我按你的步骤加入freeng 还是不行呢 
1. npm install freeng --save
2. 主模块中 import {AccordionModule} from 'freeng/freeng'; //accordion
3. @import "../node_modules/font-awesome/css/font-awesome.min.css";
@import '../node_modules/freeng/resources/freeng.min.css';
@import '../node_modules/freeng/resources/themes/blue.css';

**Comment by IronPans** [comment]
@TorettoLong 样式引入是否正确？还是有报错？请说明具体的错误。

**Comment by RonadoLong** [comment]
ERROR in AccordionModule is not an NgModule 映入之后标签无法识别

**Comment by IronPans** [comment]
@TorettoLong 随便修改一下项目（任何一个文件，打个换行也行），让它重新编译就不会出现这个问题了
